### ISSUE TITLE
Comparison parameters

### ISSUE THREAD

**Issue by mathiassmichno** [randomchain/paper#21]
Determine some factors or dimensions, which can be used to compare different approaches to generating trustable randomness.

Let's discuss in here!

Cool guys?

**Comment by SebRKri** [comment]
Hi guys, 
Methinks the Input and Verifiability factors are the most important here. 
Especially if input is essentially "input source", i.e. where it gets the entropy from.

**Comment by mToft** [comment]
The following was mentioned at the supervisor meeting:
- Attacker model
  - What can an attacker do?
  - Attack vectors
    - Availability
    - Integrity of the output (bias in the output)
      - Verifiability?
      - or in other way make sure the number is "good"
- Participation model
  - How do people interact and provide entropy?
  - Direct interaction, e.g. unicorn; indirect, e.g. π-beacon
- Trust assumptions on the input and output
