### ISSUE TITLE
Use cases to introduction

### ISSUE THREAD

**Issue by mathiassmichno** [randomchain/paper#22]
Maybe we should merge use cases into the introduction section as Stefan suggests.
Perhaps as a subsection or written into the text.

I vote for subsection

**Comment by mToft** [comment]
+1 for subsection

**Comment by SebRKri** [comment]
Hi guys, you don't usually see a lot of subsections in introductions - it breaks up the flow of the introduction. 
An alternative could be a shorter introduction, with the usecases separate, as things are somewhat muddled right now.

**Comment by SebRKri** [comment]
Hi guys,

I removed a lot of the existing usecases from the introduction in /baconintroduction, as it was getting too long and loose. 
If you approve of it this probably won't be very fitting for the intro anymore.
