### ISSUE TITLE
Make rabin great again

### ISSUE THREAD

**Issue by mathiassmichno** [randomchain/paper#97]
Elaborate on rabin and the basic def. of randomness beacon

**Comment by mToft** [comment]
Entropy is needed for most use cases. Not as a security property for the beacon. Unpredictability is the entire idea behind a random beacon. Entropy is just a nice thing to have for most use cases. "This work is concerned with the trust, and not with the entropy"???

**Comment by mathiassmichno** [comment]
But couldn't high entropy be seen as a trust factor, i.e. guarantee that the outcome is not bias? or is that "well-distributed"?

**Comment by mToft** [comment]
Unpredictability + Unbiased = properties for a beacon
Entropy is for output

**Comment by mToft** [comment]
lawl
